name: RouterOS Module Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/modules/**'
      - 'test/**'
      - '.github/workflows/module_test.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/modules/**'
      - 'test/**'
  workflow_dispatch:
    inputs:
      test_with_real_router:
        description: 'Test with real RouterOS device'
        required: false
        default: false
        type: boolean
  
jobs:
  validate-modules:
    name: Validate VLAN Modules
    runs-on: ubuntu-latest
    
    steps:    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
        check-latest: true
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.7'
        terraform_wrapper: false
    
    - name: Run module syntax and structure tests
      working-directory: test
      run: |
        chmod +x exec.sh
        ./exec.sh